import {useEffect,useMemo,useState} from 'react';
import {Activity,AlertTriangle,Bot,Boxes,Briefcase,Building2,CheckCircle2,Code2,CreditCard,FileCheck,FlaskConical,FolderOpen,Gauge,Globe,Hexagon,Home,Key,Layers,Megaphone,MessageCircle,Monitor,Network,Phone,Play,Plus,Rocket,Rss,Send,Server,Settings,Shield,Sparkles,Target,Trash2,TrendingUp,Users,Workflow,Zap} from 'lucide-react';
import {Area,AreaChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';

const C={bg:'#06060a',s1:'#0b0b12',s2:'#101018',s3:'#16161f',bd:'#202030',ac:'#00ddb5',tx:'#eaeaf4',sb:'#8080a0',dm:'#484868',dg:'#f43f5e',wn:'#f59e0b',in:'#3b82f6',pp:'#8b5cf6',pk:'#ec4899',cy:'#06b6d4',em:'#10b981'};
const now=Date.now();
const trend=[{m:'Oct',v:11.2},{m:'Nov',v:11.8},{m:'Dec',v:12.4},{m:'Jan',v:12.1},{m:'Feb',v:13.1},{m:'Mar',v:13.2},{m:'Apr',v:13.2}];
const seed:any={
  workspace:{id:'ws1',name:'GEM Cybersecurity Workspace',status:'active',plan:'enterprise'},
  projects:[
    {id:'p1',name:'Bentley Showcase',slug:'bentley-showcase',organization_name:'GEM Cybersecurity',status:'production',runtime:'Vercel',repo:'support371/Bentley-Showcase',url:'https://bentley-showcase.vercel.app',owner:'GEM Cybersecurity',tech_stack:'React, Vite, Vercel Functions'},
    {id:'p2',name:'Nexus Financial',slug:'nexus-financial',organization_name:'GEM Cybersecurity',status:'staging',runtime:'Vercel',repo:'support371/nexus-financial',url:'https://nexus-financial.vercel.app',owner:'Finance Ops',tech_stack:'React, Node.js, PostgreSQL'},
    {id:'p3',name:'OpenGuardians Portal',slug:'openguardians',organization_name:'OpenGuardians',status:'development',runtime:'Vercel',repo:'support371/openguardians',url:'https://openguardians.vercel.app',owner:'Community Ops',tech_stack:'Next.js, Redis, Docker'}
  ],
  projectTools:[
    {id:'tool1',project_id:'p1',name:'Production Frontend',category:'production',status:'healthy',owner:'Engineering',connected_service:'Vercel',last_run_at:now-600000,description:'Live customer-facing frontend and serverless API.'},
    {id:'tool2',project_id:'p1',name:'Deploy Pipeline Guard',category:'automation',status:'active',owner:'DevOps',connected_service:'GitHub + Vercel',last_run_at:now-720000,description:'Build validation, release gate, deployment monitoring.'},
    {id:'tool3',project_id:'p1',name:'Daily Cyber Digest',category:'marketing',status:'active',owner:'Marketing',connected_service:'Telegram + WhatsApp',last_run_at:now-3600000,description:'AI-assisted content digest and channel publishing workflow.'},
    {id:'tool4',project_id:'p1',name:'Bentley iModel Sync',category:'production',status:'active',owner:'Digital Twin Team',connected_service:'Bentley iTwin',last_run_at:now-120000,description:'Tracks model sync, metadata, annotations, and viewer readiness.'},
    {id:'tool5',project_id:'p1',name:'AI Agent Console',category:'ai',status:'active',owner:'Platform',connected_service:'GEM Orchestrator',last_run_at:now-240000,description:'Architect, Sentinel, Analyst, and Codex task routing workspace.'},
    {id:'tool6',project_id:'p2',name:'Ledger Reconciliation',category:'automation',status:'active',owner:'Finance Ops',connected_service:'PostgreSQL Jobs',last_run_at:now-10800000,description:'Daily financial reconciliation automation.'},
    {id:'tool7',project_id:'p3',name:'Community Digest',category:'marketing',status:'paused',owner:'Community',connected_service:'Email + Social',last_run_at:now-86400000,description:'Weekly member update pipeline.'}
  ],
  productionServices:[
    {id:'svc1',project_id:'p1',name:'GEM Enterprise Frontend',environment:'production',status:'healthy',url:'https://bentley-showcase.vercel.app',provider:'Vercel',latest_commit:'9a4be8c',actions:['view','redeploy','logs']},
    {id:'svc2',project_id:'p1',name:'Serverless API Layer',environment:'production',status:'healthy',url:'/api/status',provider:'Vercel Functions',latest_commit:'940a279',actions:['health','logs']},
    {id:'svc3',project_id:'p1',name:'iTwin Metadata Adapter',environment:'production',status:'ready',url:'/api/itwin/models',provider:'GEM API',latest_commit:'940a279',actions:['sync','logs']},
    {id:'svc4',project_id:'p2',name:'Nexus Financial API',environment:'staging',status:'monitoring',url:'https://nexus-financial.vercel.app/api',provider:'Vercel',latest_commit:'b2e9f1a',actions:['view','promote']}
  ],
  teamMembers:[
    {id:'tm1',project_id:'p1',name:'Gem Admin',email:'gem@admin.io',role:'Owner',status:'active'},
    {id:'tm2',project_id:'p1',name:'Engineering Lead',email:'eng@gem.io',role:'Developer',status:'active'},
    {id:'tm3',project_id:'p1',name:'Marketing Manager',email:'marketing@gem.io',role:'Marketing Manager',status:'active'},
    {id:'tm4',project_id:'p1',name:'Operations Analyst',email:'ops@gem.io',role:'Operator',status:'active'},
    {id:'tm5',project_id:'p2',name:'Finance Operator',email:'finance@gem.io',role:'Operator',status:'active'}
  ],
  activityLogs:[
    {id:'act1',project_id:'p1',actor:'system',event:'Deployment completed',detail:'Production deployment is READY on Vercel.',ts:now-300000,status:'success'},
    {id:'act2',project_id:'p1',actor:'DevOps',event:'Build guard passed',detail:'PostCSS blocker removed and Vite build completed.',ts:now-600000,status:'success'},
    {id:'act3',project_id:'p1',actor:'Marketing',event:'Digest queued',detail:'Cyber digest prepared for social/channel distribution.',ts:now-3600000,status:'queued'},
    {id:'act4',project_id:'p1',actor:'Digital Twin',event:'iModel sync checked',detail:'Civil Infrastructure Hub synced successfully.',ts:now-120000,status:'success'}
  ],
  deployments:[
    {id:'dp1',project_id:'p1',app_name:'Bentley Showcase',status:'deployed',environment_name:'Production',version:'v4.0.0',commit_sha:'9a4be8c'},
    {id:'dp2',project_id:'p1',app_name:'GEM API Layer',status:'deployed',environment_name:'Production',version:'v4.0.0',commit_sha:'940a279'},
    {id:'dp3',project_id:'p2',app_name:'Nexus Financial',status:'deployed',environment_name:'Staging',version:'v2.8.0',commit_sha:'b2e9f1a'},
    {id:'dp4',project_id:'p3',app_name:'OpenGuardians',status:'building',environment_name:'Development',version:'v1.4.0',commit_sha:'c7d4e3b'}
  ],
  environments:[
    {id:'en1',project_id:'p1',name:'Production',project_name:'Bentley Showcase',type:'production',status:'healthy',region:'iad1'},
    {id:'en2',project_id:'p1',name:'Preview',project_name:'Bentley Showcase',type:'preview',status:'healthy',region:'iad1'},
    {id:'en3',project_id:'p2',name:'Staging',project_name:'Nexus Financial',type:'staging',status:'healthy',region:'us-east-1'}
  ],
  integrations:[
    {id:'ig1',project_id:'p1',integration_name:'GitHub',integration_type:'cicd',status:'connected'},
    {id:'ig2',project_id:'p1',integration_name:'Vercel',integration_type:'deployment',status:'connected'},
    {id:'ig3',project_id:'p1',integration_name:'Bentley iTwin',integration_type:'digital_twin',status:'connected'},
    {id:'ig4',project_id:'p1',integration_name:'Telegram Bot',integration_type:'channel',status:'connected'},
    {id:'ig5',project_id:'p1',integration_name:'WhatsApp Cloud',integration_type:'channel',status:'pending'},
    {id:'ig6',project_id:'p1',integration_name:'Slack',integration_type:'notification',status:'connected'}
  ],
  securityEvents:[
    {id:'se1',project_id:'p1',type:'Brute Force',source_ip:'185.220.101.45',target:'Auth API',severity:'critical',status:'Blocked'},
    {id:'se2',project_id:'p1',type:'SQL Injection',source_ip:'103.45.67.89',target:'Data API',severity:'high',status:'Investigating'},
    {id:'se3',project_id:'p1',type:'DDoS Spike',source_ip:'Multiple',target:'Gateway',severity:'high',status:'Mitigated'}
  ],
  alerts:[
    {id:'al1',project_id:'p1',title:'High Error Rate',severity:'Critical',status:'Active',source:'Auth API'},
    {id:'al2',project_id:'p1',title:'SSL Cert Expiring',severity:'High',status:'Acknowledged',source:'Cert Monitor'},
    {id:'al3',project_id:'p2',title:'Memory Pressure',severity:'Medium',status:'Active',source:'K8s Cluster'}
  ],
  imodels:[
    {id:'im1',project_id:'p1',name:'Civil Infrastructure Hub',iTwin:'Smart City Alpha',size:'2.4 GB',lastSync:now-120000,status:'Synced',elements:142890,type:'Infrastructure'},
    {id:'im2',project_id:'p1',name:'Roads & Bridges Network',iTwin:'Transport Grid',size:'1.8 GB',lastSync:now-900000,status:'Synced',elements:98340,type:'Transport'},
    {id:'im3',project_id:'p1',name:'Digital Twin Facility A',iTwin:'Bentley Connect',size:'4.1 GB',lastSync:now-3600000,status:'Synced',elements:287410,type:'Facility'}
  ],
  itwinApps:[
    {id:'ta1',project_id:'p1',name:'3D Infrastructure Viewer',type:'Viewer',status:'Deployed',environment:'Production',version:'v2.1.0'},
    {id:'ta2',project_id:'p1',name:'Bridge Inspector',type:'Inspector',status:'Deployed',environment:'Staging',version:'v1.3.0'},
    {id:'ta3',project_id:'p1',name:'Asset Dashboard',type:'Dashboard',status:'Building',environment:'Development',version:'v0.4.0'}
  ],
  botChannels:[
    {id:'bc1',project_id:'p1',name:'MyGemAssist_Bot',platform:'telegram',channel:'@mycybersecureWealthsolution',status:'active',subscribers:247,messagesTotal:3842},
    {id:'bc2',project_id:'p1',name:'GEM WhatsApp',platform:'whatsapp',channel:'+1-650-555-1234',status:'pending',subscribers:89,messagesTotal:1204}
  ],
  orchestratorJobs:[
    {id:'oj1',project_id:'p1',task:'Analyze Q2 cybersecurity threat landscape',classification:'general',executor:'gpt-4o',status:'completed'},
    {id:'oj2',project_id:'p1',task:'Generate Next.js edge middleware for RBAC',classification:'software',executor:'gpt-4.1',status:'completed'},
    {id:'oj3',project_id:'p1',task:'Design automation workflow for KYC processing',classification:'workflow',executor:'claude-sonnet',status:'completed'},
    {id:'oj4',project_id:'p1',task:'Build portfolio rebalance signal engine',classification:'software',executor:'gpt-4.1',status:'running'}
  ],
  contentDigest:[
    {id:'cd1',project_id:'p1',title:'Critical CVE-2026-1234 in OpenSSL',source:'CISA',category:'cybersecurity',status:'published'},
    {id:'cd2',project_id:'p1',title:'Housing Market Q1 2026: 8.4% YoY Growth',source:'Zillow Research',category:'real_estate',status:'published'},
    {id:'cd3',project_id:'p1',title:'Fed Holds Rates Steady at 4.25%',source:'Reuters',category:'market_intelligence',status:'draft'}
  ]
};
const nav:any=[['WORKSPACE',[['home','Command Center',Home],['project-control','Project Control',FolderOpen]]],['BUILD',[['agents','AI Agents',Bot],['genesis','Genesis',Sparkles],['imodels','iModel Explorer',Hexagon],['itwinApps','iTwin Apps',Boxes]]],['OPERATE',[['bots','Bots & Channels',MessageCircle],['threats','Threats',Shield],['alerts','Alerts',AlertTriangle],['deployments','Deployments',Rocket],['health','Health',Monitor]]],['BUSINESS',[['marketing','Marketing',Megaphone],['automations','Automations',Zap],['production','Production Services',Server],['integrations','Integrations',Network],['team','Team Access',Users]]],['SYSTEM',[['tests','E2E Tests',FlaskConical],['settings','Settings',Settings]]]];
const button={display:'inline-flex',gap:6,alignItems:'center',background:C.s3,border:'1px solid '+C.bd,borderRadius:8,color:C.tx,padding:'8px 11px',cursor:'pointer',fontWeight:800,fontSize:11};
const input={background:C.s1,border:'1px solid '+C.bd,borderRadius:8,color:C.tx,padding:9,fontSize:11};
const stamp=(ts:any)=>{const s=Math.floor((Date.now()-Number(ts||0))/1000);return s<60?s+'s ago':s<3600?Math.floor(s/60)+'m ago':s<86400?Math.floor(s/3600)+'h ago':Math.floor(s/86400)+'d ago'};
function tone(s:any){s=String(s||'');return /critical|fail|error|blocked/i.test(s)?C.dg:/high|pending|ack|outdated|build|queued|review/i.test(s)?C.wn:/active|healthy|deploy|sync|connect|cert|publish|complete|success|ready|production/i.test(s)?C.em:/running|investigate|progress|monitor/i.test(s)?C.in:C.dm}
function Pill({t}:any){return <span style={{fontSize:9,fontWeight:800,color:tone(t),background:tone(t)+'22',borderRadius:5,padding:'2px 7px',whiteSpace:'nowrap'}}>{String(t)}</span>}
function Card({children,style,onClick}:any){return <div onClick={onClick} style={{background:C.s2,border:'1px solid '+C.bd,borderRadius:12,padding:14,cursor:onClick?'pointer':'default',...style}}>{children}</div>}
function H({title,children}:any){return <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10,margin:'0 0 12px'}}><h2 style={{fontSize:11,color:C.sb,letterSpacing:1,textTransform:'uppercase'}}>{title}</h2>{children}</div>}
function Kpi({label,value,icon:Icon,c}:any){return <Card><div style={{display:'flex',justifyContent:'space-between',fontSize:10,color:C.sb}}><span>{label}</span><Icon size={16} color={c}/></div><div style={{fontSize:24,fontWeight:900,marginTop:8}}>{value}</div></Card>}
function List({title,items,icon:Icon}:any){return <div><H title={title}/><div style={{display:'flex',flexDirection:'column',gap:6}}>{items.map((x:any,i:number)=><Card key={x.id||i} style={{padding:10}}><div style={{display:'flex',gap:8,alignItems:'center'}}><Icon size={14} color={tone(x.status||x.severity||x.category)}/><div style={{flex:1,minWidth:0}}><div style={{fontSize:11,fontWeight:800,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{x.title||x.name||x.app_name||x.task||x.type||x.event}</div><div style={{fontSize:9,color:C.dm}}>{x.source||x.environment_name||x.executor||x.target||x.connected_service||x.detail||x.channel}</div></div><Pill t={x.status||x.severity||x.category||x.classification}/></div></Card>)}</div></div>}
function scoped(D:any,pid:string,key:string){return (D[key]||[]).filter((x:any)=>!x.project_id||x.project_id===pid)}
function addActivity(setD:any,pid:string,event:string,detail:string,status='success'){setD((p:any)=>({...p,activityLogs:[{id:'act_'+Date.now().toString(36),project_id:pid,actor:'operator',event,detail,ts:Date.now(),status},...(p.activityLogs||[])]}))}
function HomeView({D,setSection,setProject}:any){const projects=D.projects||[];return <div><div style={{display:'flex',alignItems:'center',gap:10,marginBottom:18}}><div style={{width:42,height:42,borderRadius:12,background:'linear-gradient(135deg,'+C.ac+','+C.pp+')',display:'grid',placeItems:'center',fontWeight:900,color:C.bg}}>G</div><div><div style={{fontSize:20,fontWeight:900}}>GEM Enterprise Workspace</div><div style={{fontSize:11,color:C.dm}}>Manage applications, tools, production services, automations, marketing, teams, and activity from one operating environment.</div></div><div style={{marginLeft:'auto'}}><Pill t='Workspace Active'/></div></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:10,marginBottom:16}}><Kpi label='Projects' value={projects.length} icon={FolderOpen} c={C.ac}/><Kpi label='Production Services' value={(D.productionServices||[]).length} icon={Server} c={C.em}/><Kpi label='Tools' value={(D.projectTools||[]).length} icon={Briefcase} c={C.pp}/><Kpi label='Automations' value={(D.projectTools||[]).filter((x:any)=>x.category==='automation').length} icon={Zap} c={C.wn}/><Kpi label='Team Members' value={(D.teamMembers||[]).length} icon={Users} c={C.in}/><Kpi label='Open Alerts' value={(D.alerts||[]).filter((a:any)=>a.status==='Active').length} icon={AlertTriangle} c={C.dg}/></div><H title='Managed Projects'/><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(310px,1fr))',gap:10}}>{projects.map((p:any)=><Card key={p.id} onClick={()=>{setProject(p.id);setSection('project-control')}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><div><div style={{fontSize:15,fontWeight:900}}>{p.name}</div><div style={{fontSize:10,color:C.dm}}>{p.repo} · {p.runtime}</div></div><Pill t={p.status}/></div><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:7,marginTop:12}}><Mini k='Tools' v={scoped(D,p.id,'projectTools').length}/><Mini k='Prod' v={scoped(D,p.id,'productionServices').length}/><Mini k='Team' v={scoped(D,p.id,'teamMembers').length}/><Mini k='Events' v={scoped(D,p.id,'activityLogs').length}/></div><button style={{...button,marginTop:12,background:C.ac,color:C.bg}}><FolderOpen size={13}/>Open Control Center</button></Card>)}</div></div>}
function Mini({k,v}:any){return <div style={{background:C.s3,border:'1px solid '+C.bd,borderRadius:9,padding:8,textAlign:'center'}}><b>{v}</b><div style={{fontSize:8,color:C.dm}}>{k}</div></div>}
function ProjectControl({D,setD,projectId,setProjectId}:any){const p=(D.projects||[]).find((x:any)=>x.id===projectId)||D.projects[0];const[tab,setTab]=useState('overview');const tools=scoped(D,p.id,'projectTools');const services=scoped(D,p.id,'productionServices');const members=scoped(D,p.id,'teamMembers');const logs=scoped(D,p.id,'activityLogs');const run=(name:string)=>addActivity(setD,p.id,name,'Manual action queued and recorded for this project.','queued');const categories=['overview','production','marketing','automations','integrations','team','activity','settings'];return <div><div style={{display:'flex',gap:10,alignItems:'center',marginBottom:14}}><div style={{flex:1}}><div style={{fontSize:20,fontWeight:900}}>{p.name}</div><div style={{fontSize:11,color:C.dm}}>{p.repo} · {p.url} · {p.tech_stack}</div></div><select style={input} value={p.id} onChange={e=>setProjectId(e.target.value)}>{D.projects.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select><Pill t={p.status}/></div><div style={{display:'flex',gap:6,flexWrap:'wrap',marginBottom:14}}>{categories.map(c=><button key={c} onClick={()=>setTab(c)} style={{...button,background:tab===c?C.ac:C.s3,color:tab===c?C.bg:C.tx,textTransform:'capitalize'}}>{c}</button>)}</div>{tab==='overview'&&<div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:10,marginBottom:12}}><Kpi label='Tools' value={tools.length} icon={Briefcase} c={C.pp}/><Kpi label='Prod Services' value={services.length} icon={Server} c={C.em}/><Kpi label='Team' value={members.length} icon={Users} c={C.in}/><Kpi label='Deployments' value={scoped(D,p.id,'deployments').length} icon={Rocket} c={C.ac}/><Kpi label='Integrations' value={scoped(D,p.id,'integrations').length} icon={Network} c={C.cy}/></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:10}}><List title='Tool Catalog' items={tools} icon={Briefcase}/><List title='Production Services' items={services} icon={Server}/><List title='Activity Timeline' items={logs.slice(0,5)} icon={Activity}/></div></div>}{tab==='production'&&<ToolPanel title='Production Services' items={services} icon={Server} action={run}/>} {tab==='marketing'&&<ToolPanel title='Marketing Tools' items={tools.filter((x:any)=>x.category==='marketing')} icon={Megaphone} action={run}/>} {tab==='automations'&&<ToolPanel title='Automation Tools' items={tools.filter((x:any)=>x.category==='automation')} icon={Zap} action={run}/>} {tab==='integrations'&&<ToolPanel title='Integrations' items={scoped(D,p.id,'integrations')} icon={Network} action={run}/>} {tab==='team'&&<TeamPanel D={D} setD={setD} projectId={p.id}/>} {tab==='activity'&&<ToolPanel title='Activity Logs' items={logs} icon={Activity} action={run}/>} {tab==='settings'&&<ProjectSettings project={p}/>}</div>}
function ToolPanel({title,items,icon:Icon,action}:any){return <div><H title={title}><button style={button} onClick={()=>action('Project action') }><Play size={13}/>Run Action</button></H><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(310px,1fr))',gap:10}}>{items.map((x:any)=><Card key={x.id}><div style={{display:'flex',gap:10,alignItems:'flex-start'}}><Icon size={18} color={tone(x.status||x.category)}/><div style={{flex:1}}><div style={{fontSize:14,fontWeight:900}}>{x.name||x.integration_name||x.event}</div><div style={{fontSize:10,color:C.dm,marginTop:2}}>{x.description||x.detail||x.connected_service||x.integration_type||x.url}</div></div><Pill t={x.status||x.category}/></div><div style={{display:'flex',gap:6,marginTop:12,flexWrap:'wrap'}}><button style={button} onClick={()=>action('Open '+(x.name||x.integration_name||x.event))}>Open</button><button style={button} onClick={()=>action('Run '+(x.name||x.integration_name||x.event))}><Play size={12}/>Run</button><button style={button} onClick={()=>action('View logs for '+(x.name||x.integration_name||x.event))}>Logs</button></div></Card>)}</div></div>}
function TeamPanel({D,setD,projectId}:any){const[form,setForm]=useState({name:'',email:'',role:'Viewer'});const rows=scoped(D,projectId,'teamMembers');function add(){if(!form.name)return;setD((p:any)=>({...p,teamMembers:[{id:'tm_'+Date.now().toString(36),project_id:projectId,status:'active',...form},...(p.teamMembers||[])],activityLogs:[{id:'act_'+Date.now().toString(36),project_id:projectId,actor:'admin',event:'Team member added',detail:form.name+' added as '+form.role,ts:Date.now(),status:'success'},...(p.activityLogs||[])]}));setForm({name:'',email:'',role:'Viewer'})}return <div><H title='Team Access'><button style={{...button,background:C.ac,color:C.bg}} onClick={add}><Plus size={13}/>Add Member</button></H><Card style={{marginBottom:10}}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 160px',gap:8}}><input style={input} placeholder='Name' value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input style={input} placeholder='Email' value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><select style={input} value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{['Owner','Admin','Developer','Operator','Marketing Manager','Viewer','Auditor'].map(r=><option key={r}>{r}</option>)}</select></div></Card><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:10}}>{rows.map((m:any)=><Card key={m.id}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><div><b>{m.name}</b><div style={{fontSize:10,color:C.dm}}>{m.email}</div></div><Pill t={m.role}/></div><div style={{fontSize:10,color:C.em,marginTop:8}}>● {m.status}</div></Card>)}</div></div>}
function ProjectSettings({project}:any){return <Card>{[['Project',project.name],['Repository',project.repo],['Runtime',project.runtime],['Production URL',project.url],['Owner',project.owner],['Stack',project.tech_stack]].map(r=><div key={r[0]} style={{display:'flex',justifyContent:'space-between',fontSize:12,padding:8,borderBottom:'1px solid '+C.bd}}><span style={{color:C.sb}}>{r[0]}</span><b>{r[1]}</b></div>)}</Card>}
function Entity({title,entity,cols,D,setD,projectId}:any){const[open,setOpen]=useState(false);const[form,setForm]=useState<any>({});const rows=scoped(D,projectId,entity);function add(){const r={id:entity+'_'+Date.now().toString(36),project_id:projectId,...form,status:form.status||'active'};setD((p:any)=>({...p,[entity]:[r,...(p[entity]||[])],activityLogs:[{id:'act_'+Date.now().toString(36),project_id:projectId,actor:'operator',event:'Record created',detail:title+' record added',ts:Date.now(),status:'success'},...(p.activityLogs||[])]}));setForm({});setOpen(false)}function del(id:string){setD((p:any)=>({...p,[entity]:(p[entity]||[]).filter((r:any)=>r.id!==id)}))}return <div><H title={title}><button style={button} onClick={()=>setOpen(!open)}><Plus size={12}/>New</button></H>{open&&<Card style={{marginBottom:10}}><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:8}}>{cols.slice(0,5).map((c:string)=><input key={c} style={input} placeholder={c} value={form[c]||''} onChange={e=>setForm({...form,[c]:e.target.value})}/>)}</div><button style={{...button,background:C.ac,color:C.bg,marginTop:8}} onClick={add}>Create</button></Card>}<div style={{display:'flex',flexDirection:'column',gap:6}}>{rows.map((r:any)=><Card key={r.id} style={{padding:10}}><div style={{display:'grid',gridTemplateColumns:'repeat(5,1fr) 26px',gap:8,alignItems:'center'}}>{cols.slice(0,5).map((c:string)=><div key={c} style={{fontSize:10,color:c===cols[0]?C.tx:C.sb,fontWeight:c===cols[0]?800:500,overflow:'hidden',textOverflow:'ellipsis'}}>{/status|severity|plan|category/.test(c)?<Pill t={r[c]||'-'}/>:String(r[c]??'-')}</div>)}<button onClick={()=>del(r.id)} style={{background:'none',border:0,color:C.dm,cursor:'pointer'}}><Trash2 size={13}/></button></div></Card>)}</div></div>}
function Agents({setD,projectId}:any){const A:any=[['Architect',Layers,C.ac],['Sentinel',Shield,C.dg],['Analyst',TrendingUp,C.in],['Codex',Code2,C.pp]];const[a,setA]=useState(A[0]);const[msg,setMsg]=useState('');const[log,setLog]=useState<any[]>([]);function send(){if(!msg)return;const lane=msg.includes('code')?'GPT-4.1 software lane':msg.includes('workflow')?'Claude Sonnet workflow lane':'Claude Opus review lane';setLog([...log,{u:1,t:msg},{t:'Routed through '+lane+'. Output recorded into the selected project activity stream.',score:96}]);setMsg('');addActivity(setD,projectId,'AI task completed',msg,'success')}const ActiveIcon=a[1];return <div style={{display:'grid',gridTemplateColumns:'230px 1fr',gap:12,height:'calc(100vh - 90px)'}}><div style={{display:'flex',flexDirection:'column',gap:8}}>{A.map((x:any)=>{const Icon=x[1];return <Card key={x[0]} onClick={()=>setA(x)} style={{borderColor:a[0]===x[0]?x[2]:C.bd}}><Icon color={x[2]} size={18}/><b style={{marginLeft:8}}>{x[0]}</b></Card>})}</div><Card style={{display:'flex',flexDirection:'column',padding:0}}><div style={{padding:14,borderBottom:'1px solid '+C.bd,display:'flex',gap:8}}><ActiveIcon color={a[2]}/><b>{a[0]}</b><span style={{marginLeft:'auto',fontSize:10,color:C.dm}}>score 96 · project-scoped</span></div><div style={{flex:1,padding:14,overflow:'auto'}}>{log.map((m,i)=><div key={i} style={{margin:'8px 0',marginLeft:m.u?'auto':0,maxWidth:'75%',background:m.u?C.ac+'22':C.s3,border:'1px solid '+C.bd,borderRadius:10,padding:10,fontSize:12}}>{m.t}{m.score&&<div style={{fontSize:9,color:C.dm}}>score:{m.score}</div>}</div>)}</div><div style={{display:'flex',gap:8,padding:12,borderTop:'1px solid '+C.bd}}><input style={{...input,flex:1}} value={msg} onChange={e=>setMsg(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder='Send task to project orchestrator...'/><button style={{...button,background:C.ac,color:C.bg}} onClick={send}><Send size={14}/></button></div></Card></div>}
function Genesis(){const[p,setP]=useState('');const[r,setR]=useState<any>(null);function go(){setR({name:p||'Enterprise Command App',views:['Dashboard','Agents','Digital Twin','Messaging','Operations','Business'],agents:['Architect','Sentinel','Analyst','Codex'],security:['RBAC','audit logs','server-side AI keys']})}return <div><H title='Genesis - App Spec Generator'/><Card><textarea style={{...input,width:'100%',height:90}} value={p} onChange={e=>setP(e.target.value)} placeholder='Describe the application...'/><button style={{...button,background:C.ac,color:C.bg,marginTop:10}} onClick={go}><Sparkles size={14}/>Generate</button></Card>{r&&<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:10,marginTop:10}}>{Object.entries(r).map(([k,v]:any)=><Card key={k}><b style={{color:C.ac,textTransform:'uppercase',fontSize:11}}>{k}</b><div style={{fontSize:12,marginTop:8}}>{Array.isArray(v)?v.map((x:any)=><Pill key={x} t={x}/>):String(v)}</div></Card>)}</div>}</div>}
function IModels({D,projectId}:any){const models=scoped(D,projectId,'imodels');const[sel,setSel]=useState(models[0]);return <div style={{display:'grid',gridTemplateColumns:'250px 1fr',gap:12}}><div style={{display:'flex',flexDirection:'column',gap:8}}>{models.map((m:any)=><Card key={m.id} onClick={()=>setSel(m)} style={{borderColor:sel?.id===m.id?C.cy:C.bd}}><b>{m.name}</b><div style={{fontSize:10,color:C.dm}}>{m.iTwin} · {m.size}</div><Pill t={m.status}/></Card>)}</div><div><Card style={{height:360,background:'radial-gradient(circle at 50% 35%,#123b4d,#07070a 65%)',display:'grid',placeItems:'center'}}><div style={{width:190,height:150,border:'1px solid '+C.cy,transform:'rotateX(55deg) rotateZ(45deg)',boxShadow:'0 0 80px '+C.cy}}/></Card><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,marginTop:10}}><Card><H title='Properties'/>{Object.entries(sel||{}).map(([k,v]:any)=><div key={k} style={{display:'flex',justifyContent:'space-between',fontSize:11,padding:4,borderBottom:'1px solid '+C.bd}}><span style={{color:C.sb}}>{k}</span><span>{String(v)}</span></div>)}</Card><Card><H title='Annotations'/><div style={{fontSize:12,color:C.sb}}>Section A reinforcement, Node 4 crack, Level 2 bridge expansion joint wear.</div></Card></div></div></div>}
function Business({type,D,projectId}:any){if(type==='compliance')return <div><H title='Compliance'/>{['SOC 2 Type II','ISO 27001','GDPR','HIPAA','FedRAMP'].map((f,i)=><Card key={f} style={{marginBottom:8}}><div style={{display:'flex',alignItems:'center',gap:12}}><b style={{fontSize:22,color:i<2?C.em:i<4?C.wn:C.dg}}>{[94,88,91,72,58][i]}</b><span style={{flex:1}}>{f}</span><Pill t={i<2?'Certified':i<4?'In Review':'In Progress'}/></div></Card>)}</div>;return <div><H title={type==='marketing'?'Marketing Tools':'Investment Portfolios'}/>{type==='marketing'?<ToolPanel title='Project Marketing Tools' items={scoped(D,projectId,'projectTools').filter((x:any)=>x.category==='marketing')} icon={Megaphone} action={()=>{}}/>:<><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(160px,1fr))',gap:10,marginBottom:10}}><Kpi label='Total AUM' value='$13.2M' icon={Briefcase} c={C.in}/><Kpi label='YTD Return' value='+18.7%' icon={TrendingUp} c={C.em}/><Kpi label='Risk Score' value='42/100' icon={Gauge} c={C.pp}/><Kpi label='CAC' value='$287' icon={CreditCard} c={C.cy}/></div><Card><ResponsiveContainer height={190}><AreaChart data={trend}><XAxis dataKey='m'/><YAxis/><Tooltip/><Area dataKey='v' stroke={C.ac} fill={C.ac+'33'}/></AreaChart></ResponsiveContainer></Card></>}</div>}
function Health(){return <div><H title='Health Monitor'/><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10}}>{['Database','Auth Service','Webhook Processor','Alert Engine','Event Bus','Deploy Engine','License Service','iTwin API'].map(s=><Card key={s}><span style={{color:C.em}}>● </span><b>{s}</b><div style={{fontSize:10,color:C.em,marginTop:6}}>healthy</div></Card>)}</div></div>}
function Tests(){return <div><H title='E2E Tests'/>{['Workspace Load','Project Control Center','Tool Catalog','Team Access','Activity Logs','Production Services','Vercel Build','API Surface'].map((t,i)=><Card key={t} style={{marginBottom:6,padding:10}}><div style={{display:'flex',gap:8}}><CheckCircle2 color={C.em} size={16}/><b style={{flex:1}}>{t}</b><Pill t='PASS'/><span style={{fontSize:10,color:C.dm}}>{12+i*7}ms</span></div></Card>)}</div>}
function SettingsView(){return <Card>{[['Version','v4.1.0'],['Operating Model','Workspace → Organization → Project → Tools'],['Ready Modules','Project Control, Production, Marketing, Automation, Team, Activity'],['Deployment','Vercel-ready'],['Repository','support371/Bentley-Showcase']].map(r=><div key={r[0]} style={{display:'flex',justifyContent:'space-between',fontSize:12,padding:8,borderBottom:'1px solid '+C.bd}}><span style={{color:C.sb}}>{r[0]}</span><b>{r[1]}</b></div>)}</Card>}
export default function App(){const[section,setSection]=useState('home');const[D,setD]=useState<any>(()=>JSON.parse(localStorage.getItem('gem:v4.1:data')||'null')||seed);const[projectId,setProjectId]=useState((D.projects||seed.projects)[0].id);useEffect(()=>{localStorage.setItem('gem:v4.1:data',JSON.stringify(D))},[D]);const labels=useMemo(()=>Object.fromEntries(nav.flatMap((g:any)=>g[1].map((i:any)=>[i[0],i[1]]))),[]);function page(){if(section==='home')return <HomeView D={D} setSection={setSection} setProject={setProjectId}/>;if(section==='project-control')return <ProjectControl D={D} setD={setD} projectId={projectId} setProjectId={setProjectId}/>;if(section==='agents')return <Agents setD={setD} projectId={projectId}/>;if(section==='genesis')return <Genesis/>;if(section==='imodels')return <IModels D={D} projectId={projectId}/>;if(section==='marketing'||section==='compliance')return <Business type={section} D={D} projectId={projectId}/>;if(section==='production')return <ToolPanel title='Production Services' items={scoped(D,projectId,'productionServices')} icon={Server} action={(x:string)=>addActivity(setD,projectId,x,'Production action executed.','queued')}/>;if(section==='automations')return <ToolPanel title='Automation Tools' items={scoped(D,projectId,'projectTools').filter((x:any)=>x.category==='automation')} icon={Zap} action={(x:string)=>addActivity(setD,projectId,x,'Automation action executed.','queued')}/>;if(section==='integrations')return <ToolPanel title='Integrations' items={scoped(D,projectId,'integrations')} icon={Network} action={(x:string)=>addActivity(setD,projectId,x,'Integration action opened.','success')}/>;if(section==='team')return <TeamPanel D={D} setD={setD} projectId={projectId}/>;if(section==='health')return <Health/>;if(section==='tests')return <Tests/>;if(section==='settings')return <SettingsView/>;if(section==='bots')return <ToolPanel title='Bots & Channels' items={scoped(D,projectId,'botChannels')} icon={MessageCircle} action={(x:string)=>addActivity(setD,projectId,x,'Channel action queued.','queued')}/>;const entity=section==='threats'?'securityEvents':section;const cols=section==='deployments'?['app_name','version','environment_name','status','commit_sha']:section==='itwinApps'?['name','type','status','environment','version']:section==='alerts'?['title','severity','status','source']:section==='threats'?['type','source_ip','target','severity','status']:['name','category','status','owner','connected_service'];return <Entity title={labels[section]||section} entity={entity} cols={cols} D={D} setD={setD} projectId={projectId}/>}
return <div style={{minHeight:'100vh',background:C.bg,color:C.tx,fontFamily:'Inter,ui-sans-serif,system-ui',display:'flex'}}><style>{'body{margin:0;background:'+C.bg+'}*{box-sizing:border-box}button,input,textarea,select{font-family:inherit}::-webkit-scrollbar{width:6px}::-webkit-scrollbar-thumb{background:'+C.bd+';border-radius:9px}'}</style><aside style={{width:230,background:C.s1,borderRight:'1px solid '+C.bd,padding:10,overflow:'auto',height:'100vh',position:'sticky',top:0}}><div style={{display:'flex',gap:8,alignItems:'center',padding:8,marginBottom:8}}><div style={{width:32,height:32,borderRadius:9,display:'grid',placeItems:'center',fontWeight:900,color:C.bg,background:'linear-gradient(135deg,'+C.ac+','+C.pp+')'}}>G</div><div><b style={{fontSize:12}}>GEM Enterprise</b><div style={{fontSize:8,color:C.dm}}>Project Operating System</div></div></div>{nav.map((g:any)=><div key={g[0]} style={{marginBottom:8}}><div style={{fontSize:8,color:C.dm,fontWeight:900,letterSpacing:1,padding:'7px 8px 3px'}}>{g[0]}</div>{g[1].map((n:any)=>{const I=n[2];return <button key={n[0]} onClick={()=>setSection(n[0])} style={{width:'100%',border:0,borderRadius:8,background:section===n[0]?C.ac+'18':'transparent',color:section===n[0]?C.ac:C.sb,padding:'8px 9px',display:'flex',gap:8,alignItems:'center',cursor:'pointer',fontWeight:700,fontSize:11}}><I size={14}/>{n[1]}</button>})}</div>)}</aside><main style={{flex:1,minWidth:0}}><header style={{height:50,borderBottom:'1px solid '+C.bd,background:C.s1,display:'flex',alignItems:'center',gap:10,padding:'0 18px',position:'sticky',top:0,zIndex:2}}><b>{labels[section]||section}</b><span style={{fontSize:10,color:C.dm}}>Project: {(D.projects||[]).find((p:any)=>p.id===projectId)?.name}</span><span style={{marginLeft:'auto',fontSize:10,color:C.ac,background:C.ac+'14',padding:'4px 8px',borderRadius:6}}>workspace → project → tools</span></header><div style={{padding:16}}>{page()}</div></main></div>}
